apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  source:
    repoURL: https://github.com/svdubovik/infra.git
    path: charts/argocd
    targetRevision: main

    helm:
      valueFiles:
        - values-dev.yaml

  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default )
    syncOptions:
      - CreateNamespace=true
