apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for infrastructure services

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Allow to deploy to the any namespace in the same cluster
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc

  # Allow create any resources in cluster
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
