argo-cd:
  server:
    ingress:
      hosts:
        - argocd.dev.com

    additionalApplications:
      - name: root
        namespace: argocd
        project: default
        destination:
          server: https://kubernetes.default.svc
          namespace: default
        source:
          repoURL: https://github.com/svdubovik/argocd.git
          path: .
          targetRevision: main
          helm:
            valueFiles:
              - values-dev.yaml
        syncPolicy:
          automated:
            prune: true # Specifies if resources should be pruned during auto-syncing ( false by default )
          syncOptions:
            - CreateNamespace=true
