argo-cd:
  dex:
    enabled: false

  server:
    ingress:
      enabled: true

    extraArgs:
      - --insecure

    config:
      # https://github.com/argoproj/argo-cd/issues/1704
      resource.customizations: |
        networking.k8s.io/Ingress:
            health.lua: |
              hs = {}
              hs.status = "Healthy"
              return hs

      repositories: |
        - type: helm
          url: https://argoproj.github.io/argo-helm
          name: argo
        - type: helm
          url: https://bitnami-labs.github.io/sealed-secrets
          name: sealed-secrets
        - type: helm
          url: https://charts.bitnami.com/bitnami
          name: bitnami
        - type: helm
          url: https://kubernetes.github.io/ingress-nginx
          name: ingress-nginx
